spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mskalbania/polar-config
          default-label: main
          timeout: 3
          clone-on-start: true
          force-pull: true
server:
  port: 8888